### ISSUE TITLE
Does the mosfet board we currently have require 3.3V  or can it run off 5V?

### ISSUE THREAD

**Issue by theschweizer** [psas/reaction-control#2]
Hey guys I'm working on an AVR microcontroller for the inverted pendulum simulation of pitch and yaw and my board is using 5V.  Can the mosfet board handle that?  I noticed in eagle that there is a pin for 5V and a pin for 3.3V but the schematic refers to the 3.3V only.

**Comment by andrewgreenberg** [comment]
First, I assume you're talking about the  Solenoid Controller board. 

Second, I'm not sure what you're really asking, so I'll tell you about it, and hopefully that'll answer your question.

The solenoid controller only needs 3.3V, it doesn't need 5V. It gets the 3.3V from the "3.3V" pin that should always be provided on any  "Arduino Uno-compatible board" the solenoid controller is attached to. So while you power the Arduino with 5V, it makes the 3.3V which then powers the solenoid controller.

That all said: the solenoid controller doesn't give a rats ass what voltage it uses. If you need to plug in 5, or even 7 volts into the 3.3V line, the solenoid controller won't care, that's totally fine. Don't use anything above 10 V, though, or you risk doing bad things to the MOSFET. Why this is a terrible idea: if you put 5 or 10V on that pin from an external supply, and then plug in the solenoid controller board into an actual Arduino, you'll totally fry the Arduino.

**Comment by theschweizer** [comment]
Sorry for not being clearer.  I was referring to the solenoid control board.  I am not using an Arduino i am using an ATmega88PA MCU and it uses 5V.  I have a voltage regulator on my breadboard to convert a 9V battery power source down to 5V.  I needed to know if I need to also regulated the voltage to 3.3V for the sake of the Solenoid Controller board but it sound like I can put 5V in and be fine.

thanks.

**Comment by andrewgreenberg** [comment]
Yep, that's fine. Although now I'm curious, why are you using an ATMega88? I thought we were transitioning to Edison and/or BBB?

**Comment by theschweizer** [comment]
This is purely for show of the inverted pendulum test.  Using the
atmega88pa let's me satisfy a required project for my microcontroller class
and do work on our capstone project.  I believe Jeremy is working on
porting the roll controller to the edison from arduino.

**Comment by andrewgreenberg** [comment]
Ah! OK, great. Good luck!

**Comment by theschweizer** [comment]
Thank you.
